# Generated by Django 4.0.5 on 2022-06-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='healthproblem',
            unique_together={('name', 'degree')},
        ),
    ]
