# Generated by Django 4.0.5 on 2022-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_client_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='healthproblem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='client',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
